package cz.uhk.chemdb.utils;

import javax.inject.Named;

@Named
public enum PermissionAttribute {
    compound_K,
    compound_Smiles,
    compound_OriginalCodename,
    compound_MoleculePreview,
    compound_ION,
    compound_MW,
    compound_doi,
    compound_NOTES,
    OWNER_name,
    MELTING_POINT_all,
    DESCRIPTOR_formula,
    DESCRIPTOR_mw,
    DESCRIPTOR_hbd,
    DESCRIPTOR_hba,
    DESCRIPTOR_rb,
    DESCRIPTOR_tpsa,
    DESCRIPTOR_atoms,
    DESCRIPTOR_clogp,
    DESCRIPTOR_NMR,
    DESCRIPTOR_HRMS,
    DESCRIPTOR_purity,
    DESCRIPTOR_solubility,
    DESCRIPTOR_mol_weight,
    DESCRIPTOR_exact_mass,
    DESCRIPTOR_canonical_SMILES,
    DESCRIPTOR_InChI,
    DESCRIPTOR_num_atoms,
    DESCRIPTOR_num_bonds,
    DESCRIPTOR_num_residues,
    DESCRIPTOR_num_rotors,
    DESCRIPTOR_sequence,
    DESCRIPTOR_num_rings,
    DESCRIPTOR_logP,
    DESCRIPTOR_PSA,
    DESCRIPTOR_MR,
    SYNONYMUM_name,
    SYNONYMUM_note,
    INVITRO_all,
    INVITRO_value,
    INVITRO_value_text,
    INVITRO_target,
    INVITRO_organism,
    INVITRO_conditions,
    INVITRO_citation,
    INVITRO_doi,
    INVITRO_note,
    INVITRO_errorType,
    ATTRIBUTES_all,
    ATTRIBUTES_name,
    ATTRIBUTES_value
}
